# Generated by Django 3.0.3 on 2020-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('donator', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('CN', 'Chinese'), ('EN', 'ENGLISH')], max_length=2)),
                ('donate_date', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('prices', models.ManyToManyField(blank=True, to='donators.Price')),
            ],
        ),
    ]
